#!/usr/bin/env bash

export FIRE_ROOT=`pwd`
# the default place for dictionaries
export DICTS_ROOT="."
# debuging with efence
export EF_ALIGNMENT=32

TST=`echo "$PATH" | grep "$FIRE_ROOT"`
if [ -z "$TST" ]; then
  export PATH="$FIRE_ROOT/build:$FIRE_ROOT/Release:$FIRE_ROOT/scripts:$PATH"
fi;
